### Read Events
GET http://localhost:4004/odata/v4/events-manager/Event

### Create Event
POST http://localhost:4004/odata/v4/events-manager/Event
Content-Type: application/json

{
    "EventID": "",
    "title": "Startup Pitch Night",
    "description": "An event for startups to showcase their ideas.",
    "dateTime": "2025-10-10T18:30:00Z",
    "location": "New York, USA",
    "capacity": 300,
    "organizerId": "8e4f5b68-3c9d-4b7c-8a2d-7e35"
}